<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="generator" content="CoffeeCup HTML Editor (www.coffeecup.com)">
    <meta name="dcterms.created" content="Sun, 14 Feb 2021 18:17:07 GMT">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <title>V card</title>
    <style>
    .pink {background-color: pink;}
    <!--[if IE]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    
  </head>
  <body>
<div class= "pink">hello</div>
  </body>
</html>
